### ISSUE TITLE
A few issues I am experiencing

### ISSUE THREAD

**Issue by herohog** [brianrichins/grrlpower-comments#10]
It kinda, ALMOST works for me.
Windows 10, latest patch, HP Notebook PC, Latest patch Firefox browser.

ISSUES:
1) Doesn’t highlight all past/read comments.
2) If I click your URL it appends an new “control header” to the previous one, one per click.
3) Prev/Next buttons also seem to not be working.
4) Doesn’t seem to “remember” what was last tagged as “seen.”
5) SAVE button resets last time saved in the current session but seems to lose it on the next session.

Minor quibble: Can the highlight color be lightened up/changed to something a litter easier on the eyes?

Please feel free to contact me if you have any questions and I will do what I can to be of help. While I am rusty, I’m not clueless. I’m a retired Sr. Programmer/Analyst that specialized in integrating business data systems and processes into the Internet for both business and public facing interfaces.

THANKS so much for the effort put into doing this for us!

Speedy “HeroHog” Mercer

PS: The Page Selection buttons to the left work as well. It is the Prev/Next that don’t appear to respond to clicks for me.

**Comment by brianrichins** [comment]
Thanks for the bug reports!

1. The script highlights _new_ comments, not old ones. I haven't figured out yet how the timestamps are being generated server-side, so there is currently an overlap in the time comparisons. For example, I get comments from 1 hour before my current browser timestamp, so I assume they are in Central time. Tracking in #3.

2. The easy answer is "don't run it twice on the same page", but that's a cop-out. I noticed this as well, I'll add a check so it doesn't run twice.

3. jsDelivr is serving stale content - I originally was using a Chrome-specific scroll command but have since fixed it to use the standard one. I don't know yet how to force their CDN to clear cache, I may have to use a different provider or just have people manually load updates. :( Also, the buttons only work if there is at least one new comment on the page (hence the count displayed next to them).

4. Can you elaborate? I'm only saving a global "last read" timestamp, not the IDs of individual pages or comments, so what you're seeing may be due to #3.

5. Again, can you elaborate a bit? The displayed save time ("x minutes/hours ago") is the duration from the last save time to the current script run, so it will change between pages. Would it be clearer if I changed it to "Last saved x <units> ago"? Or have I missed the point completely?

I was also looking at different coloring - I think I'm going to drop the background color entirely and just highlight the comment border (the first ancestor `li` element). I haven't found a color I like yet; orange is the only thing that really fits the color scheme, but Dave's comments use that already. Considering `border: 3px inset orangered` for general outlines and `border: 4px inset palevioletred` for the active one.

Also really appreciate the offer to help - so far there's not a ton of things to fix though so I'm not sure what I'd even be able to have help with! I'm trying to keep the issues updated as soon as I start working on them, so if you see something unfinished in the list that you want to tackle I'll gladly take pull requests!

**Comment by herohog** [comment]
Sorry for the long delay in responding!

**Doesn’t seem to “remember” what was last tagged as “seen.”**
L if I know what I was talking about, sorry!

**SAVE button resets last time saved in the current session but seems to lose it on the next session.**
Can't duplicate in current version.

Thanks so much for looking into my issue!
